TARGET     = jsio.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../nspr/src/dist/include/nspr -I../nspr/src/dist/include/nspr/private
STATICLIBS = -L../nspr/src/dist/lib -lnspr4
SHAREDLIBS =
DEPENDS    = ../nspr/src/Makefile

include ../common/rules.mk
