TARGET     = jsio.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../nspr/nsprpub/dist/include/nspr -I../nspr/nsprpub/dist/include/nspr/private
STATICLIBS = -L../nspr/nsprpub/dist/lib -lnspr4
SHAREDLIBS =

include ../common/rules.mk
