# Build jssqlite dynamic library

def configure(conf):

    conf.check_cfg(package='sqlite3', args='--cflags --libs', atleast_version='3.6.20', uselib_store='SQLITE')

def build(bld):

    import Utils
    
    task = bld.new_task_gen('cxx', 'cshlib')
    task.target ='jssqlite'
    task.source = bld.path.ant_glob('*.cpp')
    task.includes = '../common' + ' %s/private' % bld.env.CPPPATH_NSPR[0]
    task.uselib = 'JLMOZJS NSPR SQLITE'
