TARGET=jshost
SRC=$(wildcard *.cpp)
INCLUDES=
STATICLIBS=../moduleManager/libmoduleManager.a ../jslang/jslang.a -lm
SHAREDLIBS=-ldl
DEPENDS=../host/Makefile ../jslang/Makefile

include ../common/rules.mk
