TARGET     = jsfastcgi.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../../libs/fastcgi/src/include
STATICLIBS = -L../../libs/fastcgi/??? -lz
SHAREDLIBS =
DEPENDS    = ../../libs/fastcgi/Makefile

include ../rules.mk
