#define NATIVE_READ_TRANSFORMATION_MATRIX "_NATIVE_READ_TRANSFORMATION_MATRIX"
#define NATIVE_TRANSFORMATION_MATRIX_PRIVATE "_NATIVE_TRANSFORMATION_MATRIX_PRIVATE"

typedef int (*FPReadTransformationMatrix)(void *pv, float *m);
