TARGET     = jsfastcgi.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../fastcgi/src/include
STATICLIBS = -L../fastcgi/??? -lz
SHAREDLIBS =
DEPENDS    = ../fastcgi/Makefile

include ../common/rules.mk
