TARGET     = jsz.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../../libs/zlib/$(INT_DIR)
STATICLIBS = -L../../libs/zlib/$(INT_DIR) -lz
SHAREDLIBS =
DEPENDS    = ../../libs/zlib/Makefile

include ../rules.mk
