TARGET     = jsz.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../../libs/zlib/src
STATICLIBS = -L../../libs/zlib/src -lz
SHAREDLIBS =
DEPENDS    = ../../libs/zlib/Makefile

include ../../common/rules.mk
