# Build jsz dynamic library

def configure(conf):

    conf.check_cxx(header_name='zlib.h', fragment="""
#include <stdio.h>
#include <zlib.h>
 
int main(void) {
 
  void *p;
  p=(void*)(inflate);

  if( ZLIB_VER_MAJOR    >= 1 &&
      ZLIB_VER_MINOR    >= 2 &&
      ZLIB_VER_REVISION >= 3 ) {
   
    printf("ok\\n");
    return 0;
  }
 
  return -1;
}
""", execute=True, lib='z', uselib_store='Z', msg='Checking for zlib >= 1.2.3')

def build(bld):

    import Utils
    
    task = bld.new_task_gen('cxx', 'cshlib')
    task.target ='jsz'
    task.source = bld.path.ant_glob('*.cpp')
    task.includes = '../common'
    task.uselib = 'JLMOZJS Z'
