# Build jscrypt dynamic library

def configure(conf):

    conf.check_cfg(package='libtomcrypt', args='--cflags --libs', atleast_version='1.17', uselib_store='TOMCRYPT')

def build(bld):

    import Utils
    
    task = bld.new_task_gen('cxx', 'cshlib')
    task.target ='jscrypt'
    task.source = bld.path.ant_glob('*.cpp')
    task.includes = '../common'
    task.defines = 'GMP_DESC'
    task.uselib = 'JLMOZJS TOMCRYPT'

