TARGET     = jsfont.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../../libs/freetype/src/include
STATICLIBS = -L../../libs/freetype/$(BUILD) -lfreetype
SHAREDLIBS =
DEPENDS    = ../../libs/freetype/Makefile

include ../rules.mk
