# Build jshost program

def build(bld):

    # Generate xdr
    xdr = bld.new_task_gen()
    xdr.before = 'xrdtocres'
    xdr.name = 'jstoxrd'
    xdr.source = 'embeddedBootstrapScript.js'
    xdr.target = 'embeddedBootstrapScript.js.xdr'
    xdr.rule = '${JSTOXDR} ${SRC} ${TGT} true bootstrap'

    # Generate cres
    cres = bld.new_task_gen()
    cres.name = 'xrdtocres'
    cres.source = 'embeddedBootstrapScript.js.xdr'
    cres.target = 'embeddedBootstrapScript.js.xdr.cres'
    cres.rule = '${XDRTOCRES} ${SRC} ${TGT}'
    
    # Compile jshost
    jshost = bld.new_task_gen('cxx', 'cprogram')
    jshost.target = 'jshost'
    jshost.source = bld.path.ant_glob('*.cpp')
    jshost.includes = '. ../common'
    jshost.lib = ['dl', 'pthread']
    jshost.uselib = 'JLMOZJS'
    jshost.uselib_local = ['host', 'jslang', 'nedmalloc']
