#include "stdafx.h"
#include "template.h"

BEGIN_CLASS

DEFINE_FINALIZE() {
}

DEFINE_FUNCTION( ClassConstruct ) {

	RT_ASSERT_CONSTRUCTING(thisClass);

	return JS_TRUE;
}

//DEFINE_FUNCTION( Call ) {
//	return JS_TRUE;
//}

//DEFINE_PROPERTY( prop ) {
//	return JS_TRUE;
//}

//DEFINE_FUNCTION( Func ) {
//	return JS_TRUE;
//}

	BEGIN_FUNCTION_MAP
//		FUNCTION(Func)
	END_MAP
	BEGIN_PROPERTY_MAP
//		READONLY(prop)
	END_MAP
	NO_STATIC_FUNCTION_MAP
	//BEGIN_STATIC_FUNCTION_MAP
	//END_MAP
	NO_STATIC_PROPERTY_MAP
	//BEGIN_STATIC_PROPERTY_MAP
	//END_MAP

//	NO_CLASS_CONSTRUCT
	NO_OBJECT_CONSTRUCT
//	NO_FINALIZE
	NO_CALL
	NO_PROTOTYPE
	NO_CONSTANT_MAP
	NO_INITCLASSAUX

END_CLASS( Template, NO_PRIVATE, NO_RESERVED_SLOT )

