# Build jsiconv dynamic library

def configure(conf):

    conf.check_cxx(header_name='iconv.h', function_name='iconv', uselib_store='ICONV', msg='Checking for library iconv')
    conf.check_cxx(header_name='iconv.h', function_name='iconvlist', msg='Checking for iconvlist function')
    conf.check_cxx(msg='Checking for iconv const proto', define_name="ICONV_PROTO_ARG_CONST", fragment='''
#include <iconv.h>
#include <stdlib.h>
int main() { iconv(NULL, (const char **)NULL, NULL, NULL, NULL); return 0; }
''')

def build(bld):

    defines = []
    if not bld.env.HAVE_ICONVLIST:
        defines.append('JL_NOT_HAS_ICONVLIST')
    if not bld.env.ICONV_PROTO_ARG_CONST:
        defines.append('JL_ICONV_PROTO_ARG_NOT_CONST')

    task = bld.new_task_gen('cxx', 'cshlib')
    task.target ='jsiconv'
    task.source = bld.path.ant_glob('*.cpp')
    task.includes = '../common'
    task.uselib = 'JLMOZJS ICONV'
    task.defines = defines
