TARGET     = jsio.so
SRC        = $(wildcard *.cpp)
INCLUDES   = -I../../libs/nspr/src/dist/include/nspr -I../../libs/nspr/src/dist/include/nspr/private
#STATICLIBS = -L../../libs/nspr/src/dist/lib -lnspr4
SHAREDLIBS = -L../../libs/nspr/src/dist/lib -lnspr4
DEPENDS    = ../../libs/nspr/Makefile

include ../../common/rules.mk
