# Build jsio dynamic library

def configure(conf):

    conf.check_cfg(package='xulrunner-nspr', args='--cflags --libs', atleast_version='4.8.2', uselib_store='NSPR')

def build(bld):

    import Utils
    
    task = bld.new_task_gen('cxx', 'cshlib')
    task.target ='jsio'
    task.source = bld.path.ant_glob('*.cpp')
    task.includes = '../common' + ' %s/private' % bld.env.CPPPATH_NSPR[0]
    task.uselib = 'JLMOZJS NSPR'
